services:
  # Service Backend (API FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: station_meteo_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  # Service Frontend (Serveur Web Nginx)
  frontend:
    image: nginx:alpine
    container_name: station_meteo_frontend
    ports:
      - "1200:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: always